name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_push:
    name: build_test_push
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: jonlimpw # name of Docker Hub ID
      IMAGE_NAME: simple-nodejs

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
          registry: docker.io
          tag: latest-2
          buildArgs: "DD_GIT_REPOSITORY_URL=github.com/jon94/simple-nodejs,DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
